### ISSUE TITLE
test

### ISSUE THREAD

**Issue by Rickson2019** [domomi/homer#10]
# Homer

[![N|Solid](https://cldup.com/dTxpPi9lDf.thumb.png)](https://nodesource.com/products/nsolid)

[![Build Status](https://travis-ci.org/joemccann/dillinger.svg?branch=master)](https://travis-ci.org/joemccann/dillinger)

Description goes here(Jake).

  - Type some Markdown on the left
  - See HTML in the right
  - Magic

## Short Links to Important Resources:
  - docs: handbook / roadmap (you'll learn more about this in the roadmapping session)
  - bugs: issue tracker / bug report tool
  - comms: forum link, developer list, IRC/email
## Testing: how to test the project
  1. go into the src folder: 
      >     cd src
  1. Install packages:
      >     npm install 
  1. run node and react concurrently

      >     npm run dev
  1.  If port confilct happens, change the ports in node and react respectively.
 - Change port for node-express in `/app.js`, change the port variable equal to another port other than 8080
 
      ```js 
      const port = 8080
      ```
- Change port for react in `/package.json`, change the `3000`in the `SET PORT=3000` syntax  equal to another port other than 3000
    ```json
    "scripts": {
      "start": "SET PORT=3000 && react-scripts start",
      ...
  },
    ```

**Comment by jbarrettsteiner** [comment]
Nice! @Rickson2019 🙌 “magic” 😉
