### ISSUE TITLE
Modal Issue: Notifications / Alerts user-flow 🐛

### ISSUE THREAD

**Issue by jbarrettsteiner** [domomi/homer#12]
### Describe the bug

An unexpected modal appears in the user journey. Remove entirely or replace.

### Branch version & OS

🌲 Branch: ['Cloud_Deployment'](https://github.com/domomi/homer/tree/Cloud_Deployment). 
📱 Device: iPhone 11 // software version: 13.5.1

### Steps to reproduce the behavior

1. User completes on-boarding / profile completion
2. Modal appears "Do you want us to alert you when new homes are available?"
3. Click on 'SETUP NEW HOME ALERTS'
4. See error (displays new popup related to listing a home)

### Expected behavior

As a renter user (selected as my primary role during on-boarding) I would not expect a popup to ask if I want to create a home listing. 

Secondarily the modal that was clicked on does not mention a listing, I would expect the next modal to either redirect to a "Alerts" sub-page and/or request device notification permissions.

### Actual behavior

A new modal appears asking "Where is the home you want to list" and my guess is it's a placeholder.

### Screenshots

![IMG_0915](https://user-images.githubusercontent.com/20304213/89687420-14ed5600-d8b5-11ea-9a72-f15fe869a139.PNG)
![IMG_0913](https://user-images.githubusercontent.com/20304213/89687432-1880dd00-d8b5-11ea-9f47-a91d8bc53ce3.PNG)

### Logs

No logs to attach.

### Additional context

No other context.

**Comment by Rickson2019** [comment]
Hi Jake, 

Thanks for pointing out the mistake on that page, I have fixed the problem by replace the modal with a series of toggle buttons for the user to configure the beacons. Please visit the page again and try it! 
![image](https://user-images.githubusercontent.com/56167026/89783051-2740dd00-dacb-11ea-9bd2-6d92457cdc82.png)
